name: Deploy to Server

on:
  push:
    branches:
      - main   # 👈 замість master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Sync project to server
        run: |
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ deploy@178.20.157.85:/home/deploy/time2fest

      - name: Rebuild containers
        run: |
          ssh -o StrictHostKeyChecking=no deploy@178.20.157.85 "
            cd /home/deploy/time2fest &&
            docker compose up -d --build
          "
