name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy frontend to server
        run: |
          rsync -az --delete \
            dist/ deploy@178.20.157.85:/var/www/time2fest/

      - name: Sync backend/strapi code to server
        run: |
          rsync -az --delete \
            --exclude='db-data' \
            --exclude='strapi/.env' \
            --exclude='strapi/build' \
            --exclude='**/node_modules' \
            ./ deploy@178.20.157.85:/home/deploy/time2fest

      - name: Rebuild backend/strapi containers
        run: |
          ssh -o StrictHostKeyChecking=no deploy@178.20.157.85 "
            cd /home/deploy/time2fest &&
            docker compose up -d --build
          "
